### ISSUE TITLE
serializeList? is it really serializing? how this work with onCheck

### ISSUE THREAD

**Issue by adamchenwei** [jakezatecky/react-checkbox-tree#100]
https://github.com/jakezatecky/react-checkbox-tree/blob/b4677c8c6080645d11e0304801a7f49fd23963e6/src/js/CheckboxTree.js#L77

@jakezatecky nice lib btw! Just wonder about this as I am learning about how your library works.

seems onCheck in CheckboxTree ~is a recursion and~ is calling onCheck that passed in and... it pass two instead of one argument to that onCheck... how that work? sicne first argument is serializeList (which I dont really understand why its named serialize?) also isn't 2nd argument of `node` is pretty much not been used? super confused... 

Would love some pointer on how and what this line really do.

Thank you so much! 👍

**Comment by jakezatecky** [comment]
Hello @adamchenwei, sorry for the extremely late reply. You have likely go on to much greater things, but I thought I would reply anyway.

The word **serialize** in this context is used in the broader computer science sense of translating the internal data structure used in the tree into a format that is more convenient for transmission to the caller (in this case, propagating the checked/expanded nodes to user `onCheck` and `onExpand` functions such that they can be passed to the `checked` and `expanded` properties). While serializing may often refer to taking a data structure and transcribing it into some string, in the context of this component it just means transcribing the internal hash map of nodes and their properties into a flat array of node values.

The second parameter, `node`, is supplied because there was a request by in #72 to have access the given node that was changed. It really just exists in case the caller wants to know *which* node was changed, as opposed to just having the list of all checked/expanded node values.

**Comment by jakezatecky** [comment]
Closing for now. Please let me know if you have any more questions.

**Comment by adamchenwei** [comment]
@jakezatecky thanks for the answer, it is very helpful! 

Also there is a pretty impressive ant component almost similar to yours, just thought to share 👍 
https://ant.design/components/tree-select/
enjoy!
