### ISSUE TITLE
Could we have tool tip for parents and child content

### ISSUE THREAD

**Issue by madhuyamulapalli** [jakezatecky/react-checkbox-tree#103]
Hi Jake. Thanks for the wonderful plugin. In our project we have scenario where we have longer text. Could we have tool tip option when hovered over, it shows the complete content in the tool tip. It could be a flag, so whoever need tooltip can pass true or something

**Comment by jakezatecky** [comment]
It is reasonable enough to add support for the `title` HTML attribute that would show the full text on hover. I am not very interested in rolling out a fancier tooltip, just because it is beyond the scope of the project, but I am more than happy to support `title`. I was thinking of having support for `title` on a node level as well as having a `showTooltip` property.

**Comment by madhuyamulapalli** [comment]
Thanks Jake.  Hope the enhancement will be soon in the release
