### ISSUE TITLE
Icons do not show up for basic example

### ISSUE THREAD

**Issue by A1Guy** [jakezatecky/react-checkbox-tree#104]
Hello, 
When trying to run the example, i cannot see the icons beside the tree. 
Directly invoking index.html from examples\dist also results in tree showing up without icons (empty boxes only). 
What am i missing?

**Comment by jakezatecky** [comment]
Directly opening `index.html` from the OS will make Chrome/Firefox use the `file:///` protocol, which messes with external imports in that HTML file (such as `//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css`, the CSS file that contains the icons). If you stick `https:` in front of those imports, it should work.

Doing that will change this:

![image](https://user-images.githubusercontent.com/3210703/44723774-ef3b5d80-aa9e-11e8-82b4-17060f4c331a.png)

Into this:

![image](https://user-images.githubusercontent.com/3210703/44723732-d16df880-aa9e-11e8-8ba6-faffacf941ae.png)

That's because I typically use the `//` such as `<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">`, which is not a problem when you use a web server, but it is a problem if you open the file directly up in a browser.

I suppose I can modify the HTML file to avoid this issue, but I did not envision them being opened directly.

**Comment by jakezatecky** [comment]
@A1Guy I added the HTTPS protocol to the imports which should allow you to see the icons normally if you directly open the file. Let me know if you have anymore issues.

**Comment by techuila** [comment]
The issue persist on my end. I already imported the css file as said in the instructions, but i get no icons.

**Comment by Ploppz** [comment]
I get the 

![](https://user-images.githubusercontent.com/3210703/44723774-ef3b5d80-aa9e-11e8-82b4-17060f4c331a.png)

variant on my web server. The web server is running HTTP I think. Is HTTPS required to get the fonts working?

**Comment by a2htray** [comment]
add `<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">` to `public/index.html`, it works.
