### ISSUE TITLE
Font size can't be changed!

### ISSUE THREAD

**Issue by ahmadi3d** [jakezatecky/react-checkbox-tree#167]
Hello
I can't change the font size of this component !
I tried giving style to any div i could find, but i can't change the font size , is manually editing and importing `react-checkbox-tree/lib/react-checkbox-tree.cs` the only ?
Thank you.

**Comment by jakezatecky** [comment]
There are only two rules in the included CSS that modify `font-size`. The preferred way to change the font size would be to override the default by specifying a new CSS rule like:

``` css
react-checkbox-tree {
  font-size: 18px;
}
```

Setting a parent container for the entire `CheckboxTree`  with a `style` attribute that modifies the `font-size` will unfortunately not work due to how browsers prioritize styling rules.

Alternatively, it _should_ be sufficient to wrap the labels of all the nodes with a container that modifies the font-size, although that is less elegant:

``` jsx
const nodes = {
  label: <span style="font-size: 18px">Label</span>,
  value: "value",
};
```

**Comment by jakezatecky** [comment]
Closing this issue. Let me know if the solutions above do not work.

**Comment by MohilRealloc** [comment]
> Closing this issue. Let me know if the solutions above do not work.

how can i change only desabled label color in this tree

**Comment by shreyanshkhare** [comment]
@jakezatecky could you attach a codepen/plunker link here?
