### ISSUE TITLE
Test onCheck and onExpand on jest

### ISSUE THREAD

**Issue by rjtubera** [jakezatecky/react-checkbox-tree#228]
Hi, 

How can I test onCheck and onExpand parameters on jest?

I tried to simulate click the checkbox and collapse with this

```
    wrap.find('.rct-checkbox').at(0).simulate('click')
    wrap.find('.rct-collapse').at(0).simulate('click')
```

But in my coverage it says that onCheck and OnExpand is not covered.

Can you help me please :(

**Comment by jakezatecky** [comment]
Disclaimer: I do not use Jest , so my knowledge of how Jest works is a bit weak. I just use Enzyme. However, it is my understanding that Jest can tie into Enzyme.

You should be able to test the `onCheck` and `onExpand` events directly using Enzyme in Jest using `.find('CheckboxTree').prop('onCheck')(someValue)` (and doing `.prop('onExpand')` for the `onExpand` property).

For lower-level events, the code you have looks fine for the collapse/expand buttons, but for the checkbox it would have to match against `.find('input[type="checkbox"]')`. This assumes that you are doing `mount` instead of `shallow` render in Enzyme.

**Comment by rjtubera** [comment]
Thank you @jakezatecky this worked!
