### ISSUE TITLE
right click event

### ISSUE THREAD

**Issue by arbabi2010** [jakezatecky/react-checkbox-tree#237]
Hi , I want to right click on items and open menu for it. it is possible to use  onContextMenu for every items?

**Comment by jakezatecky** [comment]
This is not supported natively by the component. However, since the `label` property for a node can be a React element, you should be able to add a context menu to any node's label.

It may make sense for this component to support a `listItemProps` property for nodes such that you can add any arbitrary properties to the node's `<li>` item (including `onContextMenu`).
