### ISSUE TITLE
Package not getting installed for react version 17.0.1

### ISSUE THREAD

**Issue by Surbhiairan** [jakezatecky/react-checkbox-tree#260]
**Describe the bug**
I have react version as 17.0.1 and this package is not getting installed. This is the error
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.1
npm WARN node_modules/react
npm WARN   react@"^17.0.1" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^15.3.0 || ^16.0.0" from react-checkbox-tree@1.6.0
npm WARN node_modules/react-checkbox-tree
npm WARN   react-checkbox-tree@"*" from the root project
npm ERR! code ENOENT
npm ERR! syscall chmod

**Reproduction steps**
1. create new react project. Make sure react version is 17.
2. Try installing this package

**Expected behavior**
Should be able to install the package on latest version as well

**Screenshots**

**Comment by jakezatecky** [comment]
Hmm. I cannot recreate this issue. If I create create a new project and run the following, I get no errors:

```
yarn add react react-dom react-checkbox-tree
```

This installs the latest React and latest checkbox tree component. There are some peer dependency warnings because this component has not been tested against React 17 (since Enzyme does not yet support it) but I see no errors.

Can you recreate a minimal project for me to clone that recreates this? Also, are you running the latest version of npm?

**Comment by jmtolibas** [comment]
Same on my end. It throws 

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: ds-material@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.3.0 || ^16.0.0" from react-checkbox-tree@1.6.0
npm ERR! node_modules/react-checkbox-tree
npm ERR!   react-checkbox-tree@"1.6.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

Does it mean it's not compatible with react 17?

**Comment by jakezatecky** [comment]
I now see that `npm` will emit an error but `yarn` will not.

As noted above, the project has not been tested with React 17 due to Enzyme not supporting itjust yet. I have been leery on adding React 17 to the peerDependencies without Enzyme providing an official adapter. Nonetheless, in my [unofficial testing](https://codesandbox.io/s/react-checkbox-tree-example-forked-2l01u?file=/src/index.js) with React 17, I have not noticed any issues. Thus, I will likely release a small update allow for React 17 in the peerDependencies.

**Comment by jakezatecky** [comment]
Resolved in 79f8b3f92876815f3b7ddef1b062b21136fbd2f8. Will push a version alter.

**Comment by af608** [comment]
Ran into the same problem -- `npm  install` is failing with:
...
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"~17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.3.0 || ^16.0.0" from react-checkbox-tree@1.6.0
npm ERR! node_modules/react-checkbox-tree
npm ERR!   react-checkbox-tree@"~1.6.0" from the root project
...
