### ISSUE TITLE
Custom checkbox selection

### ISSUE THREAD

**Issue by RodrigoCarvalho21** [jakezatecky/react-checkbox-tree#34]
HI there,

I have been wondering if it's possible to allow the checkboxes to be "uncoupled" from their parents. For instance, I have:

<pre>
A
| -- B
      | -- B1
             | -- B1.1
             | -- B1.2
      | -- B2
| -- C
</pre>

I want to select B1 without automatically select B1.1 and B1.2

Is this possible?

Many thanks!

**Comment by jakezatecky** [comment]
I suppose that's possible. It's inherently simpler than the current model. Maybe a `noCascade` option.

**Comment by jdiasamaro** [comment]
I really like the idea as well.

For instance, I have been checking the source and [here](https://github.com/jakezatecky/react-checkbox-tree/blob/master/src/js/CheckboxTree.js#L105):

```javascript
toggleChecked(node, isChecked) {
	if (node.children !== null) {
		// Percolate check status down to all children
		node.children.forEach((child) => {
			this.toggleChecked(child, isChecked);
		});
	} else {
		// Set leaf to check/unchecked state
		this.toggleNode('checked', node, isChecked);
	}
}
```

Maybe this can be achieved by conditionally executing the forEach() on the children as depicted on the code above.

However I think it would also be great to have a more general option to make all the checkboxes "loosely coupled". What do you think @jakezatecky?

**Comment by jakezatecky** [comment]
I will likely add an option for this over the weekend. Should not be too unreasonable. It does necessitate the removal of the partial check state as well, so it touches some other minor areas too. Tests will be easy.

I can name this property one of several things. I already have an option called `optimisticToggle`. It might make sense to re-purpose this into `cascadeToggle` with `optimistic`, `pessimistic`, and `none` as the possible values. Or maybe I'll just stick with `cascadeToggle={false}` or `noCascade` for user simplicity.

**Comment by jdiasamaro** [comment]
Hi,

Seems a great option.

If I might add: I think your opinion of cascadeToggle seems good. Having
the optimistic, pessimistic and none.

Btw, your library is great :)


On 19 May 2017 22:34, "Jake Zatecky" <notifications@github.com> wrote:

I will likely add an option for this over the weekend. Should not be too
unreasonable. It does necessitate the removal of the partial check state as
well, so it touches some other minor areas too. Tests will be easy.

I can name this property one of several things. I already have an option
called optimisticToggle. It might make sense to re-purpose this into
cascadeToggle with optimistic, pessimistic, and none as the possible
values. Or maybe I'll just stick with cascadeToggle={false} or noCascade
for user simplicity.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/jakezatecky/react-checkbox-tree/issues/34#issuecomment-302816736>,
or mute the thread

**Comment by jakezatecky** [comment]
Did a little work over the weekend, but the changes lack unit tests and I do not like the example I created yet. Will likely finish in the coming days.

**Comment by jakezatecky** [comment]
Although I liked the idea of `cascadeToggle` with three different options, it broke backwards compatibility, was somewhat awkward to document and build examples around, and was probably more complicated for the average user. `noCascade` has been added to fulfill this need.

**Comment by jdiasamaro** [comment]
Hi @jakezatecky,

Great! :) It's awesome now.

**Comment by jonaswindey** [comment]
It would be nice to have a different cascade policy for parent -> child and child -> parent.
I have a case where I would like to be able to select a node and have all its parents selected, but not all its children. With noCascade it's either all or nothing.
