### ISSUE TITLE
CheckboxTreeError: Duplicate value '1****' detected. All node values must be unique.

### ISSUE THREAD

**Issue by Ravindrakumara** [jakezatecky/react-checkbox-tree#384]
![image](https://user-images.githubusercontent.com/44864848/198071342-c0392728-db51-4253-a6b3-c2934761084d.png)

How to allow duplicate values; on "react-checkbox-tree": "^1.8.0", 

please let me know

**Comment by jakezatecky** [comment]
The tree requires unique values because it treats each node in the tree as distinct. There is no native support for duplicate values in this component.

That said, it is possible to append/prepend additional information to the existing duplicate values to make them unique for the tree (such as `duplicateValue0` or `/unique/path/to/duplicateValue`). You can always strip these additions when converting the values back for use _outside_ of the tree (although you need to retain them for use _inside_ the tree).
