### ISSUE TITLE
Inconsistent Id between render

### ISSUE THREAD

**Issue by KevinYobeth** [jakezatecky/react-checkbox-tree#413]
**Describe the bug**
I'm using a snapshot test from jest which snapshot the DOM and checks for the diff on every test. The problem is the id on react-checkbox-tree is always changing. Hence I can't get the constant snapshot.

**Reproduction steps**
1. Build a snapshot testing using jest.
2. Run the test
3. Run the test again, the snapshot result should be different

**Expected behavior**
Provide a way to not randomize the id, for example on MUI, we could add this snippet to lock the id randomization process
```
global.Math.random = jest.fn().mockImplementation(() => 1);
```

**Screenshots**
![image 37](https://user-images.githubusercontent.com/10485985/220821023-4134c287-a1e2-4cfb-bdcb-a3b641ea1807.png)

**Comment by jakezatecky** [comment]
If the `id` property is not set, the tree generates a random UUID with `nanoid`. When doing testing, you should supply the id property. E.g.:

``` jsx
<CheckboxTree id="test-id" ... />
```

I am looking to remove the random auto ID generation in v2.0 (a breaking change) due to a variety of reasons, one of them being the lack of consistency on render.

**Comment by KevinYobeth** [comment]
Cool, thanks! It works perfectly.
