### ISSUE TITLE
Allow additional onChecked functions

### ISSUE THREAD

**Issue by t-hughes** [jakezatecky/react-checkbox-tree#46]
Does this allow something like a show/hide input field function? For example, if I click a box, a dropdown select or input box could show up next to that item.

**Comment by jakezatecky** [comment]
Sorry, nothing like this is supported out of the box.

I suppose an additional property could be supported for the items in the `nodes` array that would allow you to arbitrarily add in any nodes (e.g. `additionalNodes`) which could be a dropdown or input box. You would then be able to programmatically display/hide those additional nodes by checking referencing the `checked` array.

This might be problematic because height of each item in the tree is very precisely aligned and additional elements could cause sizing issues.

**Comment by jakezatecky** [comment]
As it stands, this would be too complex to add and is beyond the scope of the project.
