### ISSUE TITLE
Exceptions if checked contains values not in nodes tree

### ISSUE THREAD

**Issue by kierenj** [jakezatecky/react-checkbox-tree#69]
Clearly this is a mistake in the consumer of the control, however a more graceful failure would be ideal :)

**Comment by leojhartiv** [comment]
Here's the troublesome code:
![image](https://user-images.githubusercontent.com/141352/37246354-d8a85aa0-2475-11e8-91e4-95f1ca91c067.png)

I'm using react and asynchronously loading this control's data.  The problem is that react first tries to load the control using dummy data and I also am loading the checked values via saved URL params.  Later on when my data load event occurs, the control is populated with real data and the URL params will match.  But the first time the control is loaded there will be no match.  If we could just wrap this call with a check for nullness, the problem should be resolved, no?

**Comment by jakezatecky** [comment]
It would be easy to add such a check. Would you prefer it to silently allow invalid `checked`/`expanded` values or would you like for it to log an error to the console? Or something else?

**Comment by leojhartiv** [comment]
I'd personally prefer silence, similar to how a standard HTML select works, no?  (My memory is a bit hazy on that).  Thanks!
