### ISSUE TITLE
Customizing dropdown icon?

### ISSUE THREAD

**Issue by airowe** [jakezatecky/react-checkbox-tree#76]
This is probably a dumb question, but my dropdown icon is just an empty square. I'd like it to be the FontAwesome down arrow but not sure how to edit it.

**Comment by airowe** [comment]
Importing the css file made this work. As I said, stupid question.

**Comment by airowe** [comment]
Could there be a way to customize the expand-close and expand-open icons like there is with the other icons? I'd like to have my expand and open be these, if possible:

`.rct-icon-expand-close::before {
  content: "\f0da";
}

.rct-icon-expand-open::before {
  content: "\f0d7";
}`

**Comment by jakezatecky** [comment]
Yes, you can do that. The rules you have should largely work, they would just need to be in a CSS file loaded after the `react-checkbox-tree.css` file is loaded or they would need to be put within an HTML `<style>` tag. See the JSFiddle example below:

https://jsfiddle.net/n5u2wwjg/4883/

If you are open to using Sass/Less, I could also add variables to those stylesheets for each of the component's icons such that you could merely change a Sass/Less variable and compile the CSS with those icons instead of the default. That would require me to make a quick feature change, but it's fairly trivial for me to do.

**Comment by airowe** [comment]
Worked great, thanks!
