### ISSUE TITLE
Not working with IE10

### ISSUE THREAD

**Issue by ertejaspatel** [jakezatecky/react-checkbox-tree#94]
For IE10 - it requires Crypto API - not sure why? Is there any workaround to use it with IE10?

Thanks:)

**Comment by jakezatecky** [comment]
I believe the Crypto API is being utilized by one of my dependencies, nanoid. I checked the project page and indeed there is a lack of support for IE10.

In general, I am averse to support an version below IE11. Microsoft [does not support](https://support.microsoft.com/en-us/help/17454/lifecycle-faq-internet-explorer) those versions anymore unless you are using specific Windows Server or Windows Embedded versions, which I suspect is an extremely small percentage of actual users. I understand that some businesses make the rather unusual decision to continue using unsupported versions, but if the developer of the browser does not really want to support it, then I really do not want to either. I also do not have access to IE10, which limits my ability test effectively test any issues exclusive to it.

**Comment by jakezatecky** [comment]
For the moment, I am classifying this as `wontfix` due to the lack of proper Microsoft support for IE 10.

If there is enough interest in resolving this issue for IE 10, I can look into using a different ID generator. I cannot guarantee that other IE 10-related issues that may crop up would receive the same exception, however.
